name: flashpapers
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
    - streamlit>=1.46.1
    - pydantic>=2.10.5
    - pandas>=2.2.3
    - black>=25.1.0
    - isort>=6.0.1
    - ruff>=0.12.3
    - pytest>=8.3.5
    - pytest-cov>=6.0.0
